sudo: required

services:
  - docker

script:
  - cd build-universe && ./build.sh arm && cd -
  - ./scripts/rebuild.sh arm
  - . ./build-universe/activate.sh arm
  - run ./prefix/bin/ssh -h
  - run ./prefix/bin/sshfs -h
  - cd build-universe && ./build.sh i686 && cd -
  - ./scripts/rebuild.sh i686
  - . ./build-universe/activate.sh i686
  - run ./prefix/bin/ssh -h
  - run ./prefix/bin/sshfs -h
