sudo: required

services:
  - docker

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - cd -
  - . ./build-universe/activate.sh arm
  - run ./stable/arm/ssh -V
  - run ./stable/arm/sshfs --version
  - . ./build-universe/activate.sh i686
  - run ./stable/i686/ssh -V
  - run ./stable/i686/sshfs --version
